development:
  :address: smtp.google.com
  :port: 25
  :authentication: plain
  :user_name: user
  :password: pass
production:
  :address: smtp.server.com
  :port: 25
  :authentication: plain
  :user_name: user
  :password: pass